# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='tenant_id'),
        ),
    ]
