# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_auto_20171115_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='type',
            field=models.CharField(blank=True, choices=[(b'WEBSITE', b'WEBSITE'), (b'WEIXIN', b'WEIXIN')], default=b'WEBSITE', max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='mobile'),
        ),
    ]
