# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-17 01:08
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20180208_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='type',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'WEBSITE'), ('WEIXIN', 'WEIXIN')], default='WEBSITE', max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
