# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='App Name')),
                ('send_to', models.CharField(max_length=32, verbose_name='Send To')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content')),
                ('template_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='template code')),
                ('biz_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='biz_id')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='remark')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
            ],
        ),
    ]
