# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='app_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='App Name'),
        ),
    ]
