# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20180105_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='sms',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='request_id'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url'),
        ),
    ]
