# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-09 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180906_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProduct',
        ),
        migrations.DeleteModel(
            name='DefaultProduct',
        ),
    ]
