# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:52
from __future__ import unicode_literals

import apps.product.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.product.models.get_product_pic_path, verbose_name='picture'),
        ),
    ]
