# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:37


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_pinyin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='DefaultProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('product.product',),
        ),
    ]
