# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 02:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20171212_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
