# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 01:36
from __future__ import unicode_literals

import apps.product.models
import core.django.storage
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20180817_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=core.django.storage.OverwriteStorage(), upload_to=apps.product.models.get_product_pic_path, verbose_name='picture'),
        ),
    ]
