# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_seller_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
