# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 07:16
from __future__ import unicode_literals

import core.django.db
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_seller_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='seller',
            name='schema_name',
            field=models.CharField(blank=True, default=core.django.db.get_schema_name, max_length=32),
        ),
        migrations.AlterField(
            model_name='seller',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
