# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20171107_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, choices=[(b'AU', '\u6fb3\u6d32'), (b'US', '\u5317\u7f8e'), (b'EU', '\u6fb3\u6d32'), (b'GB', '\u82f1\u56fd'), (b'JP', '\u65e5\u672c'), (b'KR', '\u97e9\u56fd'), (b'TW', '\u53f0\u6e7e'), (b'SEA', '\u4e1c\u5357\u4e9a')], default=b'AU', max_length=128, verbose_name='country'),
        ),
    ]
