# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-month']},
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='seller',
        ),
    ]
