# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('express', '0001_initial'),
        ('member', '0001_initial'),
        ('order', '0001_initial'),
        ('carrier_tracker', '0002_auto_20180907_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_orders', to='order.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='expresscarrier',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Seller'),
        ),
        migrations.AddField(
            model_name='expresscarrier',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_tracker.CarrierTracker'),
        ),
        migrations.AlterUniqueTogether(
            name='expressorder',
            unique_together=set([('carrier', 'track_id')]),
        ),
    ]
