# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('express', '0002_auto_20180904_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Address', verbose_name='address'),
        ),
    ]
