# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-11 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_auto_20180910_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expressorder',
            unique_together=set([]),
        ),
    ]
