# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_auto_20180911_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expressorder',
            options={'ordering': ['create_time']},
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='id_upload_url',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='post_search_url',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='search_url',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='expresscarrier',
            name='track_id_regex',
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_tracker.CarrierTracker'),
        ),
    ]
