# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_auto_20181023_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expresscarrier',
            name='is_default',
        ),
    ]
