# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_tracker', '0001_initial'),
        ('express', '0004_auto_20180906_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresscarrier',
            name='domain',
            field=models.CharField(blank=True, max_length=512, verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='expresscarrier',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_tracker.CarrierTracker'),
        ),
    ]
