# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_remove_expresscarrier_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresscarrier',
            name='parcel_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
