# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_auto_20180906_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresscarrier',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='expressorder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
