# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_expresscarrier_parcel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresscarrier',
            name='parcel_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='包裹数量'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='website',
            field=models.URLField(blank=True, help_text='官方网站地址', max_length=255, verbose_name='官网地址'),
        ),
        migrations.AlterField(
            model_name='expressorder',
            name='track_id',
            field=models.CharField(help_text='运单号', max_length=255, verbose_name='Track ID'),
        ),
    ]
