# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0009_auto_20171119_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresscarrier',
            name='pinyin',
            field=models.TextField(blank=True, max_length=512, verbose_name='pinyin'),
        ),
    ]
