# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0010_expresscarrier_pinyin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCarrier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('express.expresscarrier',),
        ),
        migrations.CreateModel(
            name='DefaultCarrier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('express.expresscarrier',),
        ),
    ]
