# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0011_customcarrier_defaultcarrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresscarrier',
            name='post_search_url',
            field=models.URLField(blank=True, verbose_name='Post url'),
        ),
    ]
