# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 02:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0012_expresscarrier_post_search_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresscarrier',
            name='id_upload_url',
            field=models.URLField(blank=True, help_text='\u8bc1\u4ef6\u4e0a\u4f20\u5730\u5740', verbose_name='\u8bc1\u4ef6\u4e0a\u4f20\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='is_default',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u9ed8\u8ba4', verbose_name='\u9ed8\u8ba4'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='name_cn',
            field=models.CharField(help_text='\u4e2d\u6587\u540d\u79f0', max_length=50, verbose_name='\u4e2d\u6587\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='name_en',
            field=models.CharField(blank=True, help_text='\u82f1\u6587\u540d\u79f0', max_length=50, verbose_name='\u82f1\u6587\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='post_search_url',
            field=models.URLField(blank=True, help_text='\u67e5\u8be2\u63d0\u4ea4\u7f51\u5740', verbose_name='\u67e5\u8be2\u63d0\u4ea4\u7f51\u5740'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='\u6bcf\u516c\u65a4\u8d39\u7387', max_digits=6, null=True, verbose_name='\u8d39\u7387'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='search_url',
            field=models.URLField(blank=True, help_text='\u67e5\u8be2\u7f51\u9875\u5730\u5740', verbose_name='\u67e5\u8be2\u7f51\u5740'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='track_id_regex',
            field=models.CharField(blank=True, help_text='\u8ba2\u5355\u53f7\u6b63\u5219\u8868\u8fbe\u5f0f', max_length=512, verbose_name='\u5355\u53f7\u6b63\u5219'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='website',
            field=models.URLField(blank=True, help_text='\u5b98\u65b9\u7f51\u7ad9\u5730\u5740', verbose_name='\u5b98\u7f51\u5730\u5740'),
        ),
    ]
