# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 05:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0013_auto_20180203_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresscarrier',
            name='name_cn',
            field=models.CharField(help_text='\u4e2d\u6587\u540d\u79f0', max_length=255, verbose_name='\u4e2d\u6587\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='expresscarrier',
            name='name_en',
            field=models.CharField(blank=True, help_text='\u82f1\u6587\u540d\u79f0', max_length=255, verbose_name='\u82f1\u6587\u540d\u79f0'),
        ),
    ]
