# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0016_auto_20180814_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='寄达时间'),
        ),
    ]
