# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-17 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_wxuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxpayment',
            name='trade_state',
            field=models.CharField(blank=True, choices=[('SUCCESS', '支付成功'), ('REFUND', '已退款'), ('NOTPAY', '未付款'), ('CLOSED', '支付关闭'), ('REVOKED', '已撤销'), ('USERPAYING', '支付中'), ('PAYERROR', '支付失败')], max_length=32, null=True),
        ),
    ]
