# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includes', models.CharField(max_length=255, verbose_name='includes')),
                ('excludes', models.CharField(blank=True, max_length=255, null=True, verbose_name='excludes')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('msg_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='message count')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create at')),
            ],
        ),
    ]
