# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170818_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsubscribe',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile'),
        ),
    ]
