# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 23:57


from django.db import migrations, models

def forwards_func(apps, schema_editor):
    DealSubscribe = apps.get_model("schedule", "DealSubscribe")
    DealSubscribe.objects.filter(msg_count__isnull=True).update(msg_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171130_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsubscribe',
            name='msg_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='message count'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
