# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180904_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='uid',
        ),
    ]
