# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-09 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180906_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'finish_time'},
        ),
    ]
