# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20171106_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(default=1, help_text='\u6570\u91cf', verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='cost_price_aud',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\u6210\u672c', max_digits=8, verbose_name='Cost Price AUD'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(blank=True, help_text='\u4ea7\u54c1\u540d\u79f0', max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='sell_price_rmb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\u5355\u4ef7', max_digits=8, verbose_name='Sell Price RMB'),
        ),
    ]
