# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20171119_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Address', verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='aud_rmb_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='\u4e0b\u5355\u6c47\u7387'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u652f\u4ed8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_sell_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u539f\u4ef7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_cost_aud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u8d27\u7269\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_cost_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u8d27\u7269\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profit_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u5229\u6da6'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_price_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u552e\u4ef7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5bc4\u51fa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u5feb\u9012\u8d39\u7528'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', '\u521b\u5efa'), ('CONFIRMED', '\u786e\u8ba4'), ('SHIPPING', '\u5728\u9014'), ('DELIVERED', '\u5bc4\u8fbe'), ('FINISHED', '\u5b8c\u6210'), ('CANCELED', '\u53d6\u6d88'), ('CLOSED', '\u5173\u95ed')], default='CREATED', max_length=20, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost_aud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u603b\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost_rmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u603b\u627f\u5305'),
        ),
    ]
