# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20171208_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='description',
            field=models.CharField(blank=True, help_text='\u5907\u6ce8', max_length=128, null=True, verbose_name='Description'),
        ),
    ]
