# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 23:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_msg_sent',
            field=models.BooleanField(default=False, verbose_name='delivery msg'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_msg_sent',
            field=models.BooleanField(default=False, verbose_name='send msg'),
        ),
    ]
