# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20180814_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='send_msg_sent',
            new_name='shipping_msg_sent',
        ),
    ]
