# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180819_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
