# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 05:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading_block', wagtail.wagtailcore.blocks.StructBlock((('heading_text', wagtail.wagtailcore.blocks.CharBlock(classname='Heading', required=True)), ('heading_size', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h1', 'H1'), ('h2', 'H2')])), ('heading_position', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[('center', 'Center'), ('left', 'Left')], required=False))))), ('button_block', wagtail.wagtailcore.blocks.StructBlock((('button_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('link_to_internal_page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False)), ('link_to_external_page', wagtail.wagtailcore.blocks.CharBlock(help_text='Manually enter URL  if you want the button link to an external page. This value will override the link above.', required=False)), ('button_color', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[('navy', 'Navy'), ('ice-blue', 'Ice blue'), ('violet', 'Violet'), ('aqua', 'Aqua'), ('purple', 'Purple')])), ('button_positon', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[('center', 'Center'), ('left', 'Left')], required=False))))), ('image_block', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_position', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[('center', 'Center'), ('left', 'Left')], required=False))))), ('accordion_block', wagtail.wagtailcore.blocks.StructBlock((('accordion_group_title', wagtail.wagtailcore.blocks.TextBlock(blank=True, default='', required=False)), ('accordion_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('accordion_title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('accordion_content', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))))))), ('embed_block', wagtail.wagtailcore.blocks.StructBlock((('embed', wagtail.wagtailembeds.blocks.EmbedBlock()),))), ('unorderd_list_block', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(label='Unordered list item'), icon='list-ul', template='blocks/unorderd_list_block.html')), ('orderd_list_block', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(label='Ordered list item'), icon='list-ol', template='blocks/orderd_list_block.html')), ('rich_text_block', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw_html_block', wagtail.wagtailcore.blocks.RawHTMLBlock())), blank=True, verbose_name='Page content'),
        ),
    ]
