# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-12 04:17


from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contentpage_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading_block', wagtail.wagtailcore.blocks.StructBlock([(b'heading_text', wagtail.wagtailcore.blocks.CharBlock(classname=b'Heading', required=True)), (b'heading_size', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[(b'h5', b'H5'), (b'h4', b'H4'), (b'h2', b'H2'), (b'h1', b'H1'), (b'h3', b'H3')])), (b'heading_position', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[(b'left', b'Left'), (b'center', b'Center')], required=False))])), (b'button_block', wagtail.wagtailcore.blocks.StructBlock([(b'button_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'link_to_internal_page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False)), (b'link_to_external_page', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Manually enter URL  if you want the button link to an external page. This value will override the link above.', required=False)), (b'button_color', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[(b'ice-blue', b'Ice blue'), (b'aqua', b'Aqua'), (b'purple', b'Purple'), (b'violet', b'Violet'), (b'navy', b'Navy')])), (b'button_positon', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[(b'left', b'Left'), (b'center', b'Center')], required=False))])), (b'image_block', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'image_position', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[(b'left', b'Left'), (b'center', b'Center')], required=False))])), (b'accordion_block', wagtail.wagtailcore.blocks.StructBlock([(b'accordion_group_title', wagtail.wagtailcore.blocks.TextBlock(blank=True, default=b'', required=False)), (b'accordion_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'accordion_title', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'accordion_content', wagtail.wagtailcore.blocks.RichTextBlock(required=True))])))])), (b'embed_block', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock())])), (b'unorderd_list_block', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(label=b'Unordered list item'), icon=b'list-ul', template=b'blocks/unorderd_list_block.html')), (b'orderd_list_block', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(label=b'Ordered list item'), icon=b'list-ol', template=b'blocks/orderd_list_block.html')), (b'rich_text_block', wagtail.wagtailcore.blocks.RichTextBlock()), (b'raw_html_block', wagtail.wagtailcore.blocks.RawHTMLBlock())], blank=True, verbose_name='Page content'),
        ),
    ]
