# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriertracker',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='carriertracker',
            name='rate',
        ),
        migrations.AddField(
            model_name='carriertracker',
            name='alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='carriertracker',
            name='last_track_id',
            field=models.CharField(blank=True, max_length=512, verbose_name='最新单号'),
        ),
        migrations.AddField(
            model_name='carriertracker',
            name='need_id',
            field=models.BooleanField(default=False, help_text='是否需要身份证', verbose_name='需要身份证'),
        ),
    ]
