# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_tracker', '0003_auto_20180918_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriertracker',
            name='item_tag',
        ),
        migrations.RemoveField(
            model_name='carriertracker',
            name='list_class',
        ),
        migrations.RemoveField(
            model_name='carriertracker',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='carriertracker',
            name='list_tag',
        ),
        migrations.AddField(
            model_name='carriertracker',
            name='last_succeed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后成功'),
        ),
        migrations.AddField(
            model_name='carriertracker',
            name='selector',
            field=models.CharField(blank=True, default='table tr', max_length=255, verbose_name='selector'),
        ),
        migrations.AlterField(
            model_name='carriertracker',
            name='last_track_id',
            field=models.CharField(blank=True, max_length=512, verbose_name='最后单号'),
        ),
    ]
