# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['create_time']},
        ),
        migrations.AddField(
            model_name='address',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 4, 4, 42, 38, 672921, tzinfo=utc), verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 4, 4, 42, 42, 912881, tzinfo=utc), verbose_name='Create Time'),
            preserve_default=False,
        ),
    ]
