# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:52


import apps.customer.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20171026_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id_photo_back',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.customer.models.get_id_photo_back_path, verbose_name='ID Back'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id_photo_front',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.customer.models.get_id_photo_front_path, verbose_name='ID Front'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile'),
        ),
    ]
