# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20171201_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='groupid',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='headimg_url',
            field=models.URLField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='\u624b\u673a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u8ba2\u5355\u6570'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_address', to='customer.Address', verbose_name='\u9ed8\u8ba4\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='privilege',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u5907\u6ce8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='unionid',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='weixin_id',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
