# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 01:36
from __future__ import unicode_literals

import apps.customer.models
import core.django.storage
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20180208_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id_photo_back',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=core.django.storage.OverwriteStorage(), upload_to=apps.customer.models.get_id_photo_back_path, verbose_name='ID Back'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id_photo_front',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=core.django.storage.OverwriteStorage(), upload_to=apps.customer.models.get_id_photo_front_path, verbose_name='ID Front'),
        ),
    ]
