# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 09:57


from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('messageset', '0006_auto_20161024_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcontent',
            name='contents',
            field=tinymce.models.HTMLField(blank=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='sitemailcontent',
            name='contents',
            field=tinymce.models.HTMLField(blank=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
