# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 05:42


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageset', '0007_auto_20171221_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemailcontent',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='sitemail_receivers', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u4ef6\u4eba'),
        ),
    ]
