# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-17 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageset', '0008_auto_20180430_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='标题'),
        ),
    ]
